version: "3"
services:
  nodejs:
    container_name: tv-shooter-nodejs
    build:
      context: .
      dockerfile: Dockerfile-develop
    env_file: :
      - ./production.env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/home/node/app/server
      - ./sc:/home/node/Downloads
