version: "3"
services:
  nodejs:
    container_name: tv-shooter-nodejs
    build:
      context: .
      dockerfile: Dockerfile-develop
    env_file:
      - ./dev.env
    ports:
      - "3000:3000"
      - "9231:9230"
    volumes:
      - ./server:/home/node/app/server
      - ./sc:/home/node/Downloads
